
all: c1 c2 c3 c4 c5 c6 c7 c8 m1 m2

clean:
	rm -f c1 c2 c3 c4 c5 c6 c7 c8 m1 m2 *.output

c1: ch5c1.c
	gcc -o c1 ch5c1.c -Wall

c2: ch5c2.c
	gcc -o c2 ch5c2.c -Wall

c3: ch5c3.c
	gcc -o c3 ch5c3.c -Wall

c4: ch5c4.c
	gcc -o c4 ch5c4.c -Wall

c5: ch5c5.c
	gcc -o c5 ch5c5.c -Wall

c6: ch5c6.c
	gcc -o c6 ch5c6.c -Wall

c7: ch5c7.c
	gcc -o c7 ch5c7.c -Wall

c8: ch5c8.c
	gcc -o c8 ch5c8.c -Wall

m1: ch6m1.c
	gcc -o m1 ch6m1.c -Wall

m2: ch6m2.c
	gcc -o m2 ch6m2.c -Wall
